<?php

echo $this->layout("_theme");
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="themes/adm/assets/css/styles.css">
</head>
<body>
    <div class="sidebar">
        <h2>Admin Panel</h2>
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Users</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Logout</a></li>
        </ul>
    </div>
    <div class="main-content">
        <header>
            <h1>Welcome, Admin</h1>
        </header>
        <section class="stats">
            <div class="card">
                <h3>Total Users</h3>
                <p>120</p>
            </div>
            <div class="card">
                <h3>Active Sessions</h3>
                <p>30</p>
            </div>
        </section>
        <section class="recent-activities">
            <h2>Recent Activities</h2>
            <ul>
                <li>User John Doe signed in</li>
                <li>New report generated by Sarah Smith</li>
                <li>User Jane Roe updated profile</li>
            </ul>
        </section>
    </div>
</body>
</html>